### PR TITLE
[RFC] Convert float4_neon.h to use public neon intrinsics

### PR DESCRIPTION
**Pull request by yshui**
Ref #114 

I'm not sure I've done this conversion 100% correct, so I would need your help to review it. Thanks.

### CODE REVIEW

**Comment by bkaradzic** [comment]
Don't replace float4_t with float32x4_t, make those types opaque so that it doesn't fail to build on other platforms where they don't exist.

Also don't include file inside bx namespace.

**Comment by bkaradzic** [comment]
float4_t is typeless, not unsigned/float/etc. Function defines type of operation not type of value.

**Comment by yshui** [comment]
Sorry I don't quite understand.

So you want to have a typedef float32x4_t float4_t in float4_neon.h ?

> Also don't include file inside bx namespace.

Sorry, that's a mistake.

**Comment by bkaradzic** [comment]
Yeah, you're defining:

    typedef float32x4_t float4_t;

You can just use `float4_t` in code below...

**Comment by yshui** [comment]
Thanks, I will do that.

**Comment by yshui** [comment]
BTW, can you reopen this PR, so I can push new commits to this.

**Comment by bkaradzic** [comment]
You can push fixes and open new PR.

**Pull request closed without merging**
