### PR TITLE
Support PPC64 LE Linux

### PR DESCRIPTION
**Pull request by runlevel5**
This would add a build config for PowerPC 64 Little Endian architecture with gcc

It's part of my effort to get LWJGL working for game development on the OpenPOWER platform.

Many thanks

### CODE REVIEW

**Comment by runlevel5** [comment]
@bkaradzic I hope you are well and sound. I would like to ask the PR is rejected please.

**Comment by bkaradzic** [comment]
image



You provided no description about it. So I assumed I don't have to provide reason either...

**Comment by runlevel5** [comment]
@bkaradzic my bad. Thanks for the feedback.

**Comment by runlevel5** [comment]
@bkaradzic I have just added description for the PR. If possible, would you be able to re-open the PR? Thanks for the consideration

**Comment by bkaradzic** [comment]
Which OpenPPC you're using for testing?
Do you need big endian?
Is this the only change that's needed for bgfx to work on Linux PPC or there will be more changes?

**Comment by runlevel5** [comment]
> Which OpenPPC you're using for testing?

Mainly LE variant but I do believe some devs might find BE useful.

---

>  Is this the only change that's needed for bgfx to work on Linux PPC or there will be more changes?

This is the only change.

**Comment by bkaradzic** [comment]
> Mainly LE variant but I do believe some devs might find BE useful.

I do not plan to support BE at all.

> This is the only change.

What's the difference if you just compile it with `linux-gcc` instead?

**Comment by runlevel5** [comment]
@bkaradzic the `linux-gcc` profile has build option for SSE which is not available in PowerISA

```
make  -R -C .build/projects/gmake-linux config=debug64
make: Entering directory '/home/tle/Work/bx/.build/projects/gmake-linux'
==== Building bx (debug64) ====
Creating ../../linux64_gcc/obj/x64/Debug/bx
Creating ../../linux64_gcc/obj/x64/Debug/bx/src
Creating ../../linux64_gcc/bin
allocator.cpp
g++: error: unrecognized command-line option ‘-mfpmath=sse’
g++: error: unrecognized command-line option ‘-msse2’
make[1]: *** [bx.make:441: ../../linux64_gcc/obj/x64/Debug/bx/src/allocator.o] Error 1
make: *** [Makefile:17: bx] Error 2
make: Leaving directory '/home/tle/Work/bx/.build/projects/gmake-linux'
```

**Comment by runlevel5** [comment]
> I do not plan to support BE at all.

:+1: I added a new commit to ensure that

Ref: https://github.com/runlevel5/bx/commit/0f587f319197359dd309bad2001f61fb993c16d6

**Comment by runlevel5** [comment]
>  Is this the only change that's needed for bgfx to work on Linux PPC or there will be more changes?

It should be enough to unblock me with LWJGL Pull Request https://github.com/LWJGL-CI/bgfx/pull/3

**Comment by runlevel5** [comment]
@bkaradzic great thanks for reviewing this PR.

I would like to ask if you plan to bundle ppc64le version of `genie` in `./tools/bin/linux/`? If the answer is yes, I could make a pull request

Kind regards

**Pull request merged**
