### PR TITLE
Initial Haiku support

### PR DESCRIPTION
**Pull request by extrowerk**
This patch extracted from the mame patchset: mamedev/mame#5053

### CODE REVIEW

**Comment by bkaradzic** [comment]
makefile is now broken.

Also notice BX_PLATFORM_* it's all alphabetically sorted.

**Comment by extrowerk** [comment]
Oh, let me recheck...

**Comment by bkaradzic** [comment]
See: https://github.com/bkaradzic/bx/commit/a8cf4e3b0775a2f07df4c75205bafb480ff3feff

**Comment by extrowerk** [comment]
Sorry for making you extra work, i wanted to finish it today afternoon.
Thanks.

**Comment by bkaradzic** [comment]
@extrowerk Did you ever finish this?

**Comment by bkaradzic** [comment]
There is nothing other than haiku name in scripts/toolchain.lua. Do examples work on Haiku?

**Comment by extrowerk** [comment]
I tought it is finished, isnt it?
Give me pls some days to recheck, have an exam at tuesday, so only after that can i mess with it again.

**Comment by extrowerk** [comment]
I used bx with mame, seened to work correctly. What exactly needs to be finished here?
Cant remember to the examples anymore.

**Comment by bkaradzic** [comment]
> What exactly needs to be finished here?

Haiku in toolchain.lua is mentioned only here:
https://github.com/bkaradzic/bx/blob/3c49d305e546bc9cf421e2afb9c4487170a3b7e7/scripts/toolchain.lua#L78

I don't think that works for building bx/bgfx/etc. maybe you had extra configuration for MAME?

**Comment by extrowerk** [comment]
I tried to check, but i had to see i also need genie, but afair you decided to not accept my genie patches. So idk.
What would you do in similar situation?

**Comment by bkaradzic** [comment]
There should not be any GENie changes. I assume Haiku has Clang or GCC compiler toolchain?

**Comment by extrowerk** [comment]
Yep, both available. But i posses no genie binary and what does it brings if i build one if you don't accept the patches? BX still needs genie to build.

**Comment by bkaradzic** [comment]
But with GENie it's possible to generate project files on one platform (i.e. Linux, Windows, OSX), and then copy those files and make build. Or run cross-compiler on one platform that supports GENie.

Right now there is issue that Haiku is not really buildable in any way.

**Comment by extrowerk** [comment]
While everything what you wrote is true, this doesn't helps in my case as i have no other OS, so using cross-compiling or preparing the makefiles on other supported OS ist out of question.
Idk, man, i don't want to change your pragmatic way, but i also wont change mine. I would be more than happy to nail this down as it is really cumbersome to patch the mame source tree for genie, as they already merged all my mame patches (they don't accept patches for genie). Maybe it would be much easier to purge every mention of Haiku in each of your projects and to try to convince the mame guys to use cmake or something else instead of genie.

**Pull request merged**
