### PR TITLE
musl libc support

### PR DESCRIPTION
**Pull request by ismaell**
Hopefully this isn't considered too intrusive of a change.

OS detection is done using autoconf's `config.guess`.

### CODE REVIEW

**Comment by bkaradzic** [comment]
> Hopefully this isn't considered too intrusive of a change.

It is... Not going to accept anything autoconf.

The issue is that I'm not using these tools, nor care to test with it.

My suggestion is to create your own fork of bx. bx-musl or whatever, add whatever you want there and then use that instead in your target project.

**Comment by ismaell** [comment]
My intention here is to avoid duplicated efforts; and `config.guess` is self-contained... 

Also, it might be difficult to convince MAME to take something that isn't in their upstream, and I want to avoid the distros the hassle to port this over and over again for no reason.

**Comment by bkaradzic** [comment]
I understand this, but it's offloading maintenance on me. Basically if I accepted this, after period of time you might lose all interest maintaining it, and then code would change, and someone would come to me asking me why this config.guess is broken. At which point I would just delete it. So I'm doing this preemptively. I had this problem with supporting FreeBSD, and other BSDs. So I made explicit that FreeBSD is not supported.

The issue is that MAME needs to support more platforms than I'm capable of maintaining. And my suggestion is to create one repo bgfx-mame or whatever where you would maintain all those bgfx patches that are not in main bgfx repo.

**Comment by ismaell** [comment]
I don't mean to offload the maintenance on you.  I can formally commit to maintain musl support for at least the next 5 years.

Also, please consider that `config.guess` is just a better alternative to `uname`, it won't break (it's very  careful with compatibility), and for new systems support you just copy a new version.

**Pull request closed without merging**
