### PR TITLE
Fix strnl/streol favoring \r\n when both \r\n and \n occur in the same string.

### PR DESCRIPTION
**Pull request by andr3wmac**

### CODE REVIEW

**Comment by bkaradzic** [comment]
Actually this is intentional. I should mention somewhere that function expects normalized EOLs.

**Comment by andr3wmac** [comment]
Is there a downside to the functions supporting non-normalized EOLs? I ran into this because I had a shader with \r\n on the end of it and it broke shaderc's processing.

**Comment by bkaradzic** [comment]
I think better fix would be to normalize shader code before processing.

**Comment by bkaradzic** [comment]
I added it here: https://github.com/bkaradzic/bgfx/blob/master/tools/shaderc/shaderc.cpp#L1024

Can you test it with your shader that caused problem?

**Pull request closed without merging**
