### PR TITLE
Compatible with clang-cl

### PR DESCRIPTION
**Pull request by actboy168**

### CODE REVIEW

**Comment by actboy168** [comment]
``` c++
#include <print>

int main() {
    std::println("__cplusplus={}", __cplusplus);
    std::println("_MSVC_LANG={}", _MSVC_LANG);
    return 0;
}
```

When compiled with `/std:c++latest`, clang-cl outputs:
```
__cplusplus=202400
_MSVC_LANG=202004
```

**Comment by bkaradzic** [comment]
And when you add `/Zc:__cplusplus` option?

**Comment by actboy168** [comment]
> And when you add `/Zc:__cplusplus` option?

Yes. Actually in clang-cl, `__cplusplus` always has the correct value. Even without `/Zc:__cplusplus`.

**Comment by bkaradzic** [comment]
> Yes.

Yes what?

Does `_MSVC_LANG` match `__cplusplus` once you set `/Zc:__cplusplus`?

**Comment by actboy168** [comment]
I have added `/Zc:__cplusplus`.

**Pull request closed without merging**
