### PR TITLE
Support Android NDK r23+ and arm/arm64/x86/x86_64 configurations.

### PR DESCRIPTION
**Pull request by thedmd**
This PR move Android support forward by handling Android NDK r23+ and drops older ones. GCC toolchain is gone, NDK now only have clang.

A lot of boilerplate is removed in favor of `--gcc-toolchain=` doing is job and locating all necessary includes/libs automatically.
Android dropped all variants of C++ Standard Library in favor of libc++, paths to which are also handled by above switch.

Missing x86_64 architecture was added. If there are some `-mtune` or similar flags which needs to be added, please let me know. Right now everything is left as default.

`$(ANDROID_...)` were replaced by `androidToolchainRoot()` function call, which is a bit unorthodox change. This was done, because location of toolchain depends on platform build is run on.
As a side effect builds can run on Windows cmd when using Ninja. Stripping still require running from make host.

This enable compilation of bgfx itself.

Examples need some work as `android_native_app_glue.c` included in `entry_android.cpp` no longer compile as C++.
I moved it to separate C file, but that is not enough. Condition `#if ENTRY_CONFIG_USE_NATIVE && BX_PLATFORM_ANDROID` cannot be used, because header `#include "entry_p.h"` cannot be included from C. I will need an advise how to handle this best for bgfx.

So far I tested on Windows. I post Linux and macOS results here as soon as I get to those platform later today.

In the mean time, I'm looking forward for feedback.

### CODE REVIEW

**Comment by bkaradzic** [comment]
See CI, can't require NDK environment variables in non Android builds.

**Comment by bkaradzic** [comment]
What specifically in `android_native_app_glue.c` is not C++ compatible? Maybe modifying that file wouldn't be huge change?

**Comment by thedmd** [comment]
> What specifically in `android_native_app_glue.c` is not C++ compatible? Maybe modifying that file wouldn't be huge change?

There is an implicit casts from `calloc` to `android_app*`. This change make code compile.
```diff
-struct android_app* android_app = calloc(1, sizeof(struct android_app));
+struct android_app* android_app = (struct android_app*)calloc(1, sizeof(struct android_app));
```
File is part od NDK. Path to this file is added by `toolchain.lua` in `bx` and used in `bgfx`. Corners were cut.
What I had done is to keep local copy of it in project tree. Is that viable way to put `android_native_app_glue` in `3rdparty` of `bgfx` instead?


> See CI, can't require NDK environment variables in non Android builds.

Already fixed that.

---
My mistake was using `ninja` as a generator. It is broken for Android due to `$(...)` statements in commands. And on Windows it is even more broken because cmd.exe expect `%...%` instead of `$(...)`. Also `%...%` is treated as relative path by genie so troubles were piling up.
I switched to linux box to keep focus on Android only and try to not keep `ninja` more broken than now.

**Comment by thedmd** [comment]
Companion PR was created https://github.com/bkaradzic/bgfx/pull/2960

**Comment by thedmd** [comment]
When everything will look ok I will cleanup commits and prepare PRs for final review/merge.

**Comment by thedmd** [comment]
This part is ready. PR on bgfx is setup to run Github Actions with this branch. Commit that does that will be reverted after this will be merged.

**Pull request merged**
