### PR TITLE
Add linux-ppc64le-clang profile

### PR DESCRIPTION
**Pull request by runlevel5**
For Linux distros that use clang over gcc for game development

## Changes

* Add linux-ppc64le-clang profile
* Add makefile target for both gcc and clang profiles

### CODE REVIEW

**Comment by bkaradzic** [comment]
Can you add all changes for PPC at once? Is this the last change or there is more?

**Comment by bkaradzic** [comment]
Another thing here is that PPC is very uncommon platform. It's like you, and maybe there is some other dude that also uses Haiku as his OS. :) And we already have 2 configurations for this platform that only maybe 2 people in the world will use.

**Comment by runlevel5** [comment]
> Can you add all changes for PPC at once? Is this the last change or there is more?

In consideration of your time, I try to break the change into manageable PRs that are easy for you to review. As of now, this is the last change.

> Another thing here is that PPC is very uncommon platform. It's like you, and maybe there is some other dude that also uses Haiku as his OS. :) And we already have 2 configurations for this platform that only maybe 2 people in the world will use.

Understood. The PPC community though is small but quite active. With support from IBM / RedHat there has been lots of progress and development within the community.

**Comment by runlevel5** [comment]
@bkaradzic please hold reviewing this PR. Thanks for your response in https://github.com/bkaradzic/GENie/issues/550#issuecomment-1314705538, I will make one more change to use `lld` with clang profile

**Comment by runlevel5** [comment]
@bkaradzic I could not figure out how to set linker to ldd with `premake.gcc`, let's stay with the `ld` for this PR. Therefore the PR is ready for review. Great thanks

**Comment by bkaradzic** [comment]
Looks fine, just remove changes from makefile. It's intended more for common path for most of users. PPC user could just invoke GENie and make themselves.

**Comment by runlevel5** [comment]
@bkaradzic yes I have removed all changes from makefile

**Pull request merged**
