### PR TITLE
Add unit tests for unruly functions on release builds of web

### PR DESCRIPTION
**Pull request by nathanstouffer**
# Summary

Added a unit test for `bx::sqrt`, `bx::sin`, and `bx::cos` that hit some values in the release version of web that are incorrect.

### CODE REVIEW

**Comment by bkaradzic** [comment]
So I ran this wasm unit-test and didn't reproduce the issue you're seeing...

```
../../../tests/run_test.cpp(19): Compiler: Clang 12.0.0, CPU: JIT-VM, Architecture: 32-bit, OS: asm.js 2.0.9, CRT: Clang C Library, Date: Aug  8 2022, Time: 20:16:54, C++: C++14
bx.testDebug.js:4995:19
Filters: libm bx.testDebug.html:1237:21
=============================================================================== bx.testDebug.html:1237:21
All tests passed (8587892 assertions in 1 test case)
```

Can you run it on your machine?

Only thing you need to do is modify tests/main_test.cpp to invoke `libm` test:

```cpp
static const char* s_argv[] = { "bx.test", "libm" };

int main(int _argc, const char* _argv[])
{
	return runAllTests(BX_COUNTOF(s_argv), s_argv); //_argc, _argv);
}
```

**Comment by nathan-stouffer-onx** [comment]
It looks like the code output you shared was for debug mode, but I am only seeing errors occur in wasm release builds. debug works fine. When I run the release build locally, I actually don't even get to the tests I wrote. It fails on the test for `exp`

Screen Shot 2022-08-09 at 7 54 26 AM

**Comment by bkaradzic** [comment]
```
../../../tests/run_test.cpp(19): Compiler: Clang 12.0.0, CPU: JIT-VM, Architecture: 32-bit, OS: asm.js 2.0.9, CRT: Clang C Library, Date: Aug  9 2022, Time: 06:57:44, C++: C++14
Filters: libm
===============================================================================
All tests passed (8587892 assertions in 1 test case)
```

**Comment by bkaradzic** [comment]
> When I run the release build locally, I actually don't even get to the tests I wrote. It fails on the test for exp

Open console, and get that identifier string:
`../../../tests/run_test.cpp(19): Compiler: Clang 12.0.0, CPU: JIT-VM, Architecture: 32-bit, OS: asm.js 2.0.9, CRT: Clang C Library, Date: Aug  9 2022, Time: 06:57:44, C++: C++14`

Also I ran in Firefox 103.

**Comment by bkaradzic** [comment]
This is Chromium 103.0.5060.134

```
bx.testRelease.js:4986 ../../../tests/run_test.cpp(19): Compiler: Clang 12.0.0, CPU: JIT-VM, Architecture: 32-bit, OS: asm.js 2.0.9, CRT: Clang C Library, Date: Aug  9 2022, Time: 06:57:44, C++: C++14
bx.testRelease.html:1237 Filters: libm
bx.testRelease.html:1237 ===============================================================================
bx.testRelease.html:1237 All tests passed (8587892 assertions in 1 test case)
bx.testRelease.html:1237 
```

**Comment by nathan-stouffer-onx** [comment]
oh that's very interesting. I've been testing in chrome. here's my identifier string:

`../../../tests/run_test.cpp(19): Compiler: Clang 15.0.0, CPU: JIT-VM, Architecture: 32-bit, OS: asm.js 3.1.11, CRT: Clang C Library, Date: Aug  9 2022, Time: 07:38:42, C++: C++14`

**Comment by bkaradzic** [comment]
Ok you have `Clang 15.0.0` and I have `Clang 12.0.0`.

**Comment by nathan-stouffer-onx** [comment]
that should just be the clang that comes with emscripten right?

**Comment by bkaradzic** [comment]
> that should just be the clang that comes with emscripten right?

Yes, I just upgraded it, and getting the same error. My clang is now `Clang 16.0.0`.

```
../../../tests/run_test.cpp(19): Compiler: Clang 16.0.0, CPU: JIT-VM, Architecture: 32-bit, OS: asm.js 3.1.19, CRT: Clang C Library, Date: Aug  9 2022, Time: 07:14:04, C++: C++14
Filters: libm
<empty string>
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
bx.test is a Catch v2.13.4 host application.
Run with -? for options
<empty string>
-------------------------------------------------------------------------------
libm
-------------------------------------------------------------------------------
../../../tests/math_test.cpp:63
...............................................................................
<empty string>
../../../tests/math_test.cpp:99: FAILED:
  REQUIRE( bx::isEqual(bx::exp(xx), ::expf(xx), 0.00001f) )
with expansion:
  false
<empty string>
```

**Comment by bkaradzic** [comment]
Now we need to figure out what changed with clang between 12 and 15. It could be some compiler option that was off before, became on by default.

**Comment by bkaradzic** [comment]
After switching off `-ffast-math` option in GENie script (`FloatFast`) this works again... So some optimization with fast math got more aggressive?

**Comment by nathan-stouffer-onx** [comment]
I'm guessing so. the bummer is that since there's so many header math functions, any project that consumes bx also has to have `fast-math` switched off. do you think there's any way around that?

**Comment by bkaradzic** [comment]
> do you think there's any way around that?

Yes. I just did this to identify quickly where is the issue. And I found some other projects having issues.

For example:
- https://www.mail-archive.com/llvm-bugs@lists.llvm.org/msg53681.html
- `https://github.com/llvm/llvm-project/issues/54947` (intentionally in comment so GH doesn't bother them with reference to this PR)

I need to carefully inspect code gen. My guess is I'm testing for something that becomes impossible with fast-math, and then optimizer just removes whole branch, which is not good.

**Comment by bkaradzic** [comment]
Also happens with version clang 13:

```
Apple clang version 13.1.6 (clang-1316.0.21.2.3)
Target: arm64-apple-darwin21.5.0
```

https://twitter.com/johntwolives/status/1550677694496788480

**Comment by bkaradzic** [comment]
Narrowed it down to `-fassociative-math` and `-funsafe-math-optimizations` causing the issue...

It removes branch completely in clang 14:

```cpp
		if (bits == 0
		||  bits == 2)
		{
			c0  = 1.0f;
			c2  = kCosC2;
			c4  = kCosC4;
			c6  = kCosC6;
			c8  = kCosC8;
			c10 = kCosC10;
		}
		else
		{
			c0  = xx;
			c2  = kSinC2;
			c4  = kSinC4;
			c6  = kSinC6;
			c8  = kSinC8;
			c10 = kSinC10;
		}
```

Compiler Explorer
https://godbolt.org/z/hYvK35TGj

```cpp
#include <stdint.h>

#	define BX_CONST_FUNC  __attribute__( (pure) )
#define BX_CONSTEXPR_FUNC constexpr BX_CONST_FUNC

	constexpr float kPi         = 3.1415926535897932384626433832795f;
	constexpr float kPi2        = 6.2831853071795864769252867665590f;
	constexpr float kInvPi      = 1.0f/kPi;
	constexpr float kPiHalf     = 1.5707963267948966192313216916398f;

	inline BX_CONSTEXPR_FUNC float trunc(float _a)
	{
		return float(int32_t(_a) );
	}

	inline BX_CONSTEXPR_FUNC float fract(float _a)
	{
		return _a - trunc(_a);
	}

	inline BX_CONSTEXPR_FUNC float floor(float _a)
	{
		if (_a < 0.0f)
		{
			const float fr = fract(-_a);
			const float result = -_a - fr;

			return -(0.0f != fr
				? result + 1.0f
				: result)
				;
		}

		return _a - fract(_a);
	}

	inline BX_CONSTEXPR_FUNC float square(float _a)
	{
		return _a * _a;
	}

	inline BX_CONSTEXPR_FUNC float add(float _a, float _b)
	{
		return _a + _b;
	}

	inline BX_CONSTEXPR_FUNC float mul(float _a, float _b)
	{
		return _a * _b;
	}

	inline BX_CONSTEXPR_FUNC float mad(float _a, float _b, float _c)
	{
		return add(mul(_a, _b), _c);
	}

	namespace
	{
		constexpr float kSinC2  = -0.16666667163372039794921875f;
		constexpr float kSinC4  =  8.333347737789154052734375e-3f;
		constexpr float kSinC6  = -1.9842604524455964565277099609375e-4f;
		constexpr float kSinC8  =  2.760012648650445044040679931640625e-6f;
		constexpr float kSinC10 = -2.50293279435709337121807038784027099609375e-8f;

		constexpr float kCosC2  = -0.5f;
		constexpr float kCosC4  =  4.166664183139801025390625e-2f;
		constexpr float kCosC6  = -1.388833043165504932403564453125e-3f;
		constexpr float kCosC8  =  2.47562347794882953166961669921875e-5f;
		constexpr float kCosC10 = -2.59630184018533327616751194000244140625e-7f;

	} // namespace

	BX_CONST_FUNC float cos(float _a)
	{
		const float scaled = _a * 2.0f*kInvPi;
		const float real   = floor(scaled);
		const float xx     = _a - real * kPiHalf;
		const int32_t bits = int32_t(real) & 3;

		float c0, c2, c4, c6, c8, c10;

		if (bits == 0
		||  bits == 2)
		{
			c0  = 1.0f;
			c2  = kCosC2;
			c4  = kCosC4;
			c6  = kCosC6;
			c8  = kCosC8;
			c10 = kCosC10;
		}
		else
		{
			c0  = xx;
			c2  = kSinC2;
			c4  = kSinC4;
			c6  = kSinC6;
			c8  = kSinC8;
			c10 = kSinC10;
		}

		const float xsq    = square(xx);
		const float tmp0   = mad(c10,  xsq, c8 );
		const float tmp1   = mad(tmp0, xsq, c6 );
		const float tmp2   = mad(tmp1, xsq, c4 );
		const float tmp3   = mad(tmp2, xsq, c2 );
		const float tmp4   = mad(tmp3, xsq, 1.0);
		const float result = tmp4 * c0;

		return bits == 1 || bits == 2
			? -result
			:  result
			;
	}
```

**Comment by bkaradzic** [comment]
@nathanstouffer Can you try changing https://github.com/bkaradzic/bx/blob/ba7024418ddead785687e6e1993b67e6c58b4c22/include/bx/inline/math.inl#L99-L113

to this:

```cpp
	inline float forceEval(float _a)
	{
		volatile float result = _a;
		return result;
	}

	inline BX_CONSTEXPR_FUNC float floor(float _a)
	{
		if (_a < 0.0f)
		{
			const float fr = fract(-_a);
			const float result = forceEval(-_a - fr);

			return -(0.0f != fr
				? result + 1.0f
				: result)
				;
		}

		return _a - fract(_a);
	}
```

**Comment by bkaradzic** [comment]
And a little bit cleaner fix:
https://github.com/bkaradzic/bx/blob/7ea3f88e461774979b45b058a284a6b9378a5434/include/bx/inline/math.inl#L99-L110

**Comment by nathan-stouffer-onx** [comment]
just ran that, all tests passed!

**Pull request merged**
