### PR TITLE
Added droid x86_64 setup, smoke tested OK on x86_64. 

### PR DESCRIPTION
**Pull request by sweep3r**
(and corrected default in description)

### CODE REVIEW

**Comment by bkaradzic** [comment]
Did you try building with Release64 configuration?

**Comment by sweep3r** [comment]
Yes, debug/release, tested x86_64 on mac-hosted droid simulator, pixel_2_pie_9_0 API 28, running fine, from a shared lib. Are you worried about the release-only symbol strip? Not entirely sure about that, just grabbed what the other abis were doing..

**Comment by bkaradzic** [comment]
No, what I meant if you generate android-x86, and use config=release64 (or config=debug64) that might already build for x64.

**Comment by sweep3r** [comment]
But, we have "android-arm64" already, not "android-arm" with "release64"...

**Comment by bkaradzic** [comment]
> But, we have "android-arm64" already, not "android-arm" with "release64"...

Yes, there are some legacy idiosyncrasies due to how Premake4 was treating CPU targets. `config<bitness>` is something that works everywhere else, and it uses `-m64` to setup AMD64 64-bit.

See: https://linux.die.net/man/1/gcc

**Comment by sweep3r** [comment]
Hmm, yes, so I see that release64 etc is used in the makefile, for linux, vs2017 etc. But, notably *not* used for the existing 3 ABIs for Android, nor for iOS, nor for OS X, which all split the bitness out of the config, and put it in its own ABI section, e.g. iOS-arm64-release, not iOS-arm-release64.

I see what you mean, if the toolchain can already do it, then perhaps we don't need this change, and instead build it with (android-x86,Release64).. but that would be quite inconsistent, considering I'm building arm64 with (android-arm64, Release), no?

**Comment by bkaradzic** [comment]
It is inconsistent, but it's how GENie generates configuration for Visual Studio, and makefiles. For example it just adds `-m64` for debug64/release64.

The issue here is that you're focusing only on one configuration android-x64, and trying to make one configuration consistent, while ignoring all other configuration that are inconsistent with your mindset.

For example:

```
linux-debug64                  Build - Linux x64 Debug
linux-release64                Build - Linux x64 Release
linux                          Build - Linux x86/x64 Debug and Release
freebsd-debug32                Build - FreeBSD x86 Debug
freebsd-release32              Build - FreeBSD x86 Release
freebsd-debug64                Build - FreeBSD x86 Debug
freebsd-release64              Build - FreeBSD x86 Release
freebsd                        Build - FreeBSD x86/x64 Debug and Release
mingw-gcc-debug32              Build - MinGW GCC x86 Debug
mingw-gcc-release32            Build - MinGW GCC x86 Release
mingw-gcc-debug64              Build - MinGW GCC x64 Debug
mingw-gcc-release64            Build - MinGW GCC x64 Release
mingw-gcc                      Build - MinGW GCC x86/x64 Debug and Release
mingw-clang-debug32            Build - MinGW Clang x86 Debug
mingw-clang-release32          Build - MinGW Clang x86 Release
mingw-clang-debug64            Build - MinGW Clang x64 Debug
mingw-clang-release64          Build - MinGW Clang x64 Release
mingw-clang                    Build - MinGW Clang x86/x64 Debug and Release
vs2017-debug32                 Build - vs2017 x86 Debug
vs2017-release32               Build - vs2017 x86 Release
vs2017-debug64                 Build - vs2017 x64 Debug
vs2017-release64               Build - vs2017 x64 Release
vs2017                         Build - vs2017 x86/x64 Debug and Release
```

**Comment by sweep3r** [comment]
Sorry - back to cpp, and catching up - thanks for the explanation, I shall have another go :)

**Pull request closed without merging**
